#!/bin/sh
# shellcheck shell=dash

if [ -f /etc/config/omci ]; then
	uci set omci.pon_adapter=omci
	# Only add libponimg to the list of pon_adapter modules if it is not already present
	uci show omci.pon_adapter.modules | grep -qw libponimg || uci add_list omci.pon_adapter.modules=libponimg
fi
