#!/bin/sh /etc/rc.common
START=89
USE_PROCD=1

start_service() {
	local debug_level
	local event_index
	local log
	local ptp_device
	local socket_path
	local output_mode
	local uart
	local uart_baudrate
	local disable_announce_msg

	config_load todd
	config_get debug_level "daemon" "debug_level" "3" #TOD_DBG_ERR
	config_get event_index "daemon" "event_index" "0"
	config_get log "daemon" "log" ""
	config_get ptp_device "daemon" "ptp_device" "/dev/ptp4"
	config_get socket_path "daemon" "socket_path"
	config_get output_mode "daemon" "output_mode" "GPZDA"
	config_get uart "daemon" "uart" ""
	config_get uart_baudrate "daemon" "uart_baudrate" "115200"
	config_get_bool disable_announce_msg "daemon" "disable_announce_msg" false

	if [ ! -z "$uart" ]; then
		stty -F ${uart} ${uart_baudrate} raw cs8 -cstopb -parenb
		uart="--uart $uart"
	fi

	if [ ! -z "$log" ]; then
		log="--log $log"
	fi

	if [ ! -z "$socket_path" ]; then
		socket_path="--socket_path $socket_path"
	fi

	if [ $disable_announce_msg -eq 1 ]; then
		disable_announce_msg="--disable_announce_msg"
	else
		disable_announce_msg=""
	fi

	procd_open_instance
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command /usr/bin/todd --debug_level ${debug_level} ${log} --ptp_device ${ptp_device} ${socket_path} --output_mode ${output_mode} ${uart} --event_index ${event_index} ${disable_announce_msg}
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "todd"
}
